/**
 * components/votecast/Assistant.tsx
 *
 * Matachakra AI Assistant — fully wired frontend component.
 *
 * Features:
 *  • Real API calls via TanStack Start server function (sendChatMessage).
 *  • Multi-turn conversation history for contextual follow-up questions.
 *  • Aggressive loading state with animated pulsing dots (already designed).
 *  • Voice-to-text via browser-native Web Speech API (zero cost, zero deps).
 *  • Graceful error display with retry affordance.
 *  • Markdown bold (**text**) rendering preserved from original.
 *  • Accessible: aria-live, aria-label, keyboard-navigable mic button.
 *  • Source badge: shows "Cached" vs "Gemini AI" for transparency.
 */

"use client";

import { useEffect, useRef, useState, useCallback } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Send, Sparkles, Bot, User, Mic, MicOff, AlertCircle, Database, Cpu } from "lucide-react";
import { sendChatMessage } from "@/actions/chat";
import { PollingBoothLocator } from "./PollingBoothLocator";

// ── Types ─────────────────────────────────────────────────────────────────────

type MessageSource = "firestore_cache" | "gemini" | "local" | "error";

type Message = {
  id: string;
  role: "user" | "assistant";
  content: string;
  source?: MessageSource;
};

// Mirrors the server function's history type
type ConversationTurn = { role: "user" | "model"; text: string };

// ── Browser Speech Recognition types (not in standard TS lib) ────────────────

declare global {
  interface Window {
    SpeechRecognition: typeof SpeechRecognition;
    webkitSpeechRecognition: typeof SpeechRecognition;
  }
}

// ── Constants ─────────────────────────────────────────────────────────────────

const QUICK_PROMPTS = [
  "What ID do I need?",
  "How do I find my booth?",
  "When is registration open?",
  "What if my name's missing?",
];

/** Max conversation turns to send to the server (keeps payload small). */
const MAX_HISTORY_TURNS = 6;

// ── Sub-components ────────────────────────────────────────────────────────────

function SourceBadge({ source }: { source?: MessageSource }) {
  if (!source || source === "local" || source === "error") return null;
  return (
    <span
      className={`mt-1 inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-medium ${
        source === "firestore_cache"
          ? "bg-emerald-500/10 text-emerald-400"
          : "bg-primary/10 text-primary"
      }`}
      title={
        source === "firestore_cache"
          ? "Served from Firestore cache (instant, zero AI cost)"
          : "Generated by Gemini AI"
      }
    >
      {source === "firestore_cache" ? (
        <>
          <Database className="h-2.5 w-2.5" aria-hidden /> Cached
        </>
      ) : (
        <>
          <Cpu className="h-2.5 w-2.5" aria-hidden /> Gemini AI
        </>
      )}
    </span>
  );
}

function MessageBubble({ m }: { m: Message }) {
  const isUser = m.role === "user";
  const isError = m.source === "error";

  return (
    <motion.div
      key={m.id}
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25 }}
      className={`flex items-end gap-2.5 ${isUser ? "flex-row-reverse" : "flex-row"}`}
    >
      <div
        className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${
          isUser
            ? "bg-coral text-coral-foreground"
            : isError
              ? "bg-destructive/20 text-destructive"
              : "bg-gradient-to-br from-primary to-cyan-glow text-primary-foreground"
        }`}
        aria-hidden
      >
        {isUser ? (
          <User className="h-4 w-4" />
        ) : isError ? (
          <AlertCircle className="h-4 w-4" />
        ) : (
          <Bot className="h-4 w-4" />
        )}
      </div>

      <div className={`flex flex-col ${isUser ? "items-end" : "items-start"} max-w-[80%]`}>
        <div
          className={`rounded-2xl px-4 py-3 text-sm leading-relaxed ${
            isUser
              ? "rounded-br-sm bg-primary text-primary-foreground"
              : isError
                ? "rounded-bl-sm border border-destructive/20 bg-destructive/5 text-destructive"
                : "rounded-bl-sm bg-white/[0.06] text-foreground ring-1 ring-white/10"
          }`}
        >
          {/* Render **bold** markdown inline */}
          {m.content.split("**").map((chunk, i) =>
            i % 2 === 1 ? (
              <strong key={i} className="font-semibold">
                {chunk}
              </strong>
            ) : (
              <span key={i}>{chunk}</span>
            ),
          )}
        </div>
        {!isUser && <SourceBadge source={m.source} />}
        {!isUser && (m.content.toLowerCase().includes("where") || m.content.toLowerCase().includes("booth") || m.content.toLowerCase().includes("station")) && (
          <PollingBoothLocator />
        )}
      </div>
    </motion.div>
  );
}

// ── Main Component ────────────────────────────────────────────────────────────

export function Assistant() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "welcome",
      role: "assistant",
      content:
        "Hi 👋 I'm your Matachakra assistant. Ask me anything about registering, voting, or your rights — or tap a quick prompt below to get started.",
      source: "local",
    },
  ]);

  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isListening, setIsListening] = useState(false);
  const [voiceSupported, setVoiceSupported] = useState(false);

  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const recognitionRef = useRef<SpeechRecognition | null>(null);

  // ── Auto-scroll on new messages ──────────────────────────────────────────
  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, isLoading]);

  // ── Detect voice support ─────────────────────────────────────────────────
  useEffect(() => {
    const SR = typeof window !== "undefined"
      ? window.SpeechRecognition ?? window.webkitSpeechRecognition
      : null;
    setVoiceSupported(!!SR);
  }, []);

  // ── Build conversation history for server ────────────────────────────────
  const buildHistory = useCallback((): ConversationTurn[] => {
    // Exclude the welcome message and the last user message (that's the current query)
    const relevant = messages.filter((m) => m.id !== "welcome" && m.source !== "error");
    const turns: ConversationTurn[] = relevant.map((m) => ({
      role: m.role === "user" ? "user" : "model",
      text: m.content,
    }));
    // Cap to last N turns to control payload size
    return turns.slice(-MAX_HISTORY_TURNS);
  }, [messages]);

  // ── Send message ─────────────────────────────────────────────────────────
  const send = useCallback(
    async (text: string) => {
      const trimmed = text.trim();
      if (!trimmed || isLoading) return;

      const userMsg: Message = {
        id: crypto.randomUUID(),
        role: "user",
        content: trimmed,
      };

      setMessages((m) => [...m, userMsg]);
      setInput("");
      setIsLoading(true);

      try {
        const history = buildHistory();
        const result = await sendChatMessage({
          data: { message: trimmed, conversationHistory: history },
        });

        if (result.ok) {
          setMessages((m) => [
            ...m,
            {
              id: crypto.randomUUID(),
              role: "assistant",
              content: result.answer,
              source: result.source,
            },
          ]);
        } else {
          setMessages((m) => [
            ...m,
            {
              id: crypto.randomUUID(),
              role: "assistant",
              content: result.error,
              source: "error",
            },
          ]);
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : "An unexpected error occurred.";
        setMessages((m) => [
          ...m,
          {
            id: crypto.randomUUID(),
            role: "assistant",
            content: `Sorry, I ran into a problem: ${msg} Please try again.`,
            source: "error",
          },
        ]);
      } finally {
        setIsLoading(false);
        // Refocus input for smooth UX
        setTimeout(() => inputRef.current?.focus(), 50);
      }
    },
    [isLoading, buildHistory],
  );

  // ── Voice input (Web Speech API) ─────────────────────────────────────────
  const toggleVoice = useCallback(() => {
    const SR = window.SpeechRecognition ?? window.webkitSpeechRecognition;
    if (!SR) return;

    if (isListening) {
      recognitionRef.current?.stop();
      setIsListening(false);
      return;
    }

    const recognition = new SR();
    recognition.lang = "en-IN"; // Indian English locale for better accuracy
    recognition.continuous = false;
    recognition.interimResults = true;
    recognition.maxAlternatives = 1;

    recognition.onstart = () => setIsListening(true);

    recognition.onresult = (event: SpeechRecognitionEvent) => {
      const transcript = Array.from(event.results)
        .map((r) => r[0].transcript)
        .join("");
      setInput(transcript);
    };

    recognition.onend = () => {
      setIsListening(false);
      // Auto-focus input so the user can review/edit the transcribed text
      setTimeout(() => inputRef.current?.focus(), 50);
    };

    recognition.onerror = (event: SpeechRecognitionErrorEvent) => {
      console.warn("[Matachakra] Speech recognition error:", event.error);
      setIsListening(false);
    };

    recognitionRef.current = recognition;
    recognition.start();
  }, [isListening]);

  // ── Render ───────────────────────────────────────────────────────────────
  return (
    <section id="assistant" className="relative px-6 py-20" aria-labelledby="assistant-title">
      <div className="mx-auto max-w-5xl">
        <div className="mb-10 text-center">
          <p className="mb-3 inline-flex items-center gap-2 text-sm font-semibold uppercase tracking-[0.2em] text-coral">
            <Sparkles className="h-4 w-4" aria-hidden /> AI Assistant
          </p>
          <h2 id="assistant-title" className="font-display text-4xl font-bold md:text-5xl">
            Ask anything. <span className="text-gradient-cyan">Get clear answers.</span>
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-muted-foreground">
            No jargon. No paperwork maze. Just answers to the questions every voter has.
          </p>
        </div>

        <div className="glass-strong relative overflow-hidden rounded-3xl shadow-[var(--shadow-elevated)]">
          {/* Glow accent */}
          <div
            className="pointer-events-none absolute -top-24 right-0 h-64 w-64 rounded-full opacity-40 blur-3xl"
            style={{ background: "radial-gradient(circle, var(--cyan-glow), transparent 60%)" }}
            aria-hidden
          />

          {/* Header */}
          <div className="flex items-center gap-3 border-b border-white/10 px-6 py-4">
            <div className="relative grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-primary to-cyan-glow">
              <Bot className="h-5 w-5 text-primary-foreground" aria-hidden />
              <span
                className={`absolute -bottom-0.5 -right-0.5 h-3 w-3 rounded-full ring-2 ring-background transition-colors ${
                  isLoading ? "animate-pulse bg-amber-400" : "bg-emerald-400"
                }`}
                aria-label={isLoading ? "Processing" : "Online"}
              />
            </div>
            <div>
              <p className="font-display text-sm font-semibold">Matachakra Assistant</p>
              <p className="text-xs text-muted-foreground">
                {isLoading ? "Thinking…" : "Online · responds instantly"}
              </p>
            </div>
          </div>

          {/* Messages */}
          <div
            ref={scrollRef}
            className="pretty-scroll h-[420px] overflow-y-auto px-4 py-6 sm:px-8"
            role="log"
            aria-live="polite"
            aria-label="Conversation with Matachakra assistant"
            aria-atomic="false"
          >
            <div className="space-y-4">
              <AnimatePresence initial={false}>
                {messages.map((m) => (
                  <MessageBubble key={m.id} m={m} />
                ))}
              </AnimatePresence>

              {/* Loading indicator */}
              {isLoading && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="flex items-end gap-2.5"
                  aria-label="Assistant is generating a response"
                >
                  <div className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-primary to-cyan-glow text-primary-foreground" aria-hidden>
                    <Bot className="h-4 w-4" />
                  </div>
                  <div className="rounded-2xl rounded-bl-sm bg-white/[0.06] px-4 py-3 ring-1 ring-white/10">
                    <div className="flex gap-1.5" role="status" aria-label="Loading">
                      {[0, 1, 2].map((i) => (
                        <motion.span
                          key={i}
                          className="block h-1.5 w-1.5 rounded-full bg-primary"
                          animate={{ y: [0, -4, 0] }}
                          transition={{ duration: 0.8, repeat: Infinity, delay: i * 0.15 }}
                        />
                      ))}
                    </div>
                  </div>
                </motion.div>
              )}
            </div>
          </div>

          {/* Quick prompts */}
          <div className="border-t border-white/10 px-4 pt-4 sm:px-6">
            <div className="flex flex-wrap gap-2" role="group" aria-label="Quick prompt suggestions">
              {QUICK_PROMPTS.map((q) => (
                <button
                  key={q}
                  type="button"
                  onClick={() => send(q)}
                  disabled={isLoading}
                  className="rounded-full border border-white/10 bg-white/5 px-4 py-1.5 text-xs font-medium text-muted-foreground transition-all hover:border-primary/40 hover:bg-primary/10 hover:text-foreground disabled:cursor-not-allowed disabled:opacity-50"
                  aria-label={`Ask: ${q}`}
                >
                  {q}
                </button>
              ))}
            </div>

            {/* Input row */}
            <form
              className="mt-4 flex items-center gap-2 pb-5"
              onSubmit={(e) => {
                e.preventDefault();
                send(input);
              }}
            >
              <label htmlFor="chat-input" className="sr-only">
                Type your question
              </label>
              <input
                ref={inputRef}
                id="chat-input"
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder={
                  isListening
                    ? "Listening… speak now"
                    : "Ask about registration, voting, IDs…"
                }
                disabled={isLoading}
                maxLength={500}
                className={`flex-1 rounded-full border bg-white/[0.04] px-5 py-3 text-sm text-foreground placeholder:text-muted-foreground/70 focus:outline-none focus:ring-2 disabled:cursor-not-allowed disabled:opacity-60 ${
                  isListening
                    ? "animate-pulse border-primary/60 bg-primary/5 focus:border-primary focus:ring-primary/30"
                    : "border-white/10 focus:border-primary/50 focus:bg-white/[0.06] focus:ring-primary/20"
                }`}
                aria-label="Type your question for the Matachakra assistant"
                autoComplete="off"
              />

              {/* Voice input button */}
              {voiceSupported && (
                <button
                  type="button"
                  id="voice-input-btn"
                  onClick={toggleVoice}
                  disabled={isLoading}
                  aria-label={isListening ? "Stop voice input" : "Start voice input"}
                  aria-pressed={isListening}
                  title={isListening ? "Click to stop listening" : "Click to speak your question"}
                  className={`inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-full border transition-all focus:outline-none focus:ring-2 focus:ring-primary/40 disabled:cursor-not-allowed disabled:opacity-50 ${
                    isListening
                      ? "animate-pulse border-primary/60 bg-primary/20 text-primary"
                      : "border-white/10 bg-white/[0.04] text-muted-foreground hover:border-primary/40 hover:bg-primary/10 hover:text-foreground"
                  }`}
                >
                  {isListening ? (
                    <MicOff className="h-4 w-4" aria-hidden />
                  ) : (
                    <Mic className="h-4 w-4" aria-hidden />
                  )}
                </button>
              )}

              {/* Send button */}
              <button
                type="submit"
                id="send-message-btn"
                disabled={!input.trim() || isLoading}
                aria-label="Send message"
                className="group inline-flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-primary to-cyan-glow text-primary-foreground transition-all hover:scale-105 hover:glow-primary disabled:cursor-not-allowed disabled:opacity-40 disabled:hover:scale-100 disabled:hover:shadow-none"
              >
                <Send
                  className="h-4 w-4 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5"
                  aria-hidden
                />
              </button>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
}
